templates:
  py37: &py37
  python: 3.7
  dist: xenial
  sudo: required

  django2-0: &django2-0 DJANGO=2.0
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest

virtualenv:
  system_site_packages: true