templates:
  py37: &py37
  python: 3.7
  dist: xenial
  sudo: required

  django2-0: &django2-0 DJANGO=2.0


before_install:
    - sudo apt-get -qq update
env:
  - DJANGO_VERSION=2.2.1
  
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest

virtualenv:
  system_site_packages: true